# PROBLEM SET 2

### Question 1
Consider the following Python module: 
a = 0  

def b(): 

    global a 
    
    a = c(a) 
    
def c(a): 

    return a + 2 
    
After importing the module into the interpreter, you execute: 

b() 

b() 

b() 

a 

? 

What value is displayed when the last expression (a) is evaluated? Explain your answer by indicating what happens in every executed statement.

In [3]:
a = 0 

def b(): 
    global a 
    a = c(a) 

def c(a): 
    return a + 2

b() 
b() 
b() 
a

6

### Explaination
The variable a is initially set to 0.

Each time b() is called, it calls c(a) and assigns the result to the global variable a.

Each call to c(a) adds 2 to a.

So first call to b()=a+2=0+2=2

second call= a+2=2+2=4

and Third call= a+2=6

### Question 2

Function fileLength(), given to you, takes the name of a file as input and returns 
the length of the file: 
 
fileLength('midterm.py') 

284 

fileLength('idterm.py') 

Traceback (most recent call last): 

  File "<pyshell#34>", line 1, in <module>
    
    fileLength('idterm.py') 
    
  File "/Users/me/midterm.py", line 3, in fileLength 
    
    infile = open(filename) 
    
FileNotFoundError: [Errno 2] No such file or directory: 
    
'idterm.py' 
 
As shown above, if the file cannot be found by the interpreter or if it cannot be read 
as a text file, an exception will be raised. Modify function fileLength() so that a 
friendly message is printed instead: 
 
fileLength('midterm.py') 
    
358 
    
fileLength('idterm.py') 
    
File idterm.py not found.

In [11]:
def file_length(file_name):
    try:
        with open(file_name) as file:
            contents = file.read()
        print(len(contents))
    except FileNotFoundError:
        print(f"File {file_name} not found.")

#If file is there
file_length('Filelength.txt')

#If file is not there
file_length('idterm.py')

123
File idterm.py not found.

### Question 3
Write a class named Marsupial that can be used as shown below: 
 
m = Marsupial() 

m.put_in_pouch('doll') 

m.put_in_pouch('firetruck')

m.put_in_pouch('kitten')

m.pouch_contents() 

['doll', 'firetruck', 'kitten']

Now write a class named Kangaroo as a subclass of Marsupial that inherits all the 
attributes of Marsupial and also: 
a. extends the Marsupial __init__ constructor to take, as input, the 
coordinates x and y of the Kangaroo object, 
b. supports method jump that takes number values dx and dy as input and 
moves the kangaroo by dx units along the x-axis and by dy units along the y
axis, and 
c. overloads the __str__ operator so it behaves as shown below. 
 
k = Kangaroo(0,0)

print(k) 

I am a Kangaroo located at coordinates (0,0) 

k.put_in_pouch('doll') 

k.put_in_pouch('firetruck') 

k.put_in_pouch('kitten') 

k.pouch_contents() 

['doll', 'firetruck', 'kitten'] 

k.jump(1,0) 

k.jump(1,0) 

k.jump(1,0)

print(k) 

I am a Kangaroo located at coordinates (3,0)

In [12]:
class Marsupial:
    def __init__(self):
        self.pouch = []

    def put_in_pouch(self, item):
        self.pouch.append(item)

    def pouch_contents(self):
        return self.pouch

class Kangaroo(Marsupial):
    def __init__(self, x, y):
        super().__init__()
        self.x = x
        self.y = y

    def jump(self, dx, dy):
        self.x += dx
        self.y += dy

    def __str__(self):
        return f"I am a Kangaroo located at coordinates ({self.x},{self.y})"


m = Marsupial()
m.put_in_pouch('doll')
m.put_in_pouch('firetruck')
m.put_in_pouch('kitten')
print(m.pouch_contents())

k = Kangaroo(0, 0)
print(k)
k.put_in_pouch('doll')
k.put_in_pouch('firetruck')
k.put_in_pouch('kitten')
print(k.pouch_contents())
k.jump(1, 0)
k.jump(1, 0)
k.jump(1, 0)
print(k)

['doll', 'firetruck', 'kitten']
I am a Kangaroo located at coordinates (0,0)
['doll', 'firetruck', 'kitten']
I am a Kangaroo located at coordinates (3,0)

### Question 4
Question 4 

Write function collatz() that takes a positive integer x as input and prints the 
Collatz sequence starting at x. A Collatz sequence is obtained by repeatedly applying 
this rule to the previous number x in the sequence: 

  
x = { 𝑥/2               𝑖𝑓 𝑥 𝑖𝑠 𝑒𝑣𝑒𝑛
     3𝑥+1               𝑖𝑓 𝑥 𝑖𝑠 𝑜𝑑𝑑 
 
Your function should stop when the sequence gets to number 1. Your 
implementation must be recursive, without any loops.

collatz(1) 

1 

collatz(10) 

10 

5 

16 

8 

4 

2 

1

In [16]:
def collatz(x):
    print(x)
    if x == 1:
        return
    elif x % 2 == 0:
        collatz(x // 2)
    else:
        collatz(3 * x + 1)

print("collatz(1)")    
collatz(1)
print("collatz(10)")
collatz(10)

collatz(1)
1
collatz(10)
10
5
16
8
4
2
1

### Question 5

Write a recursive method binary() that takes a non-negative 
integer n and prints the binary representation of integer n. 
 
binary(0) 

0 

binary(1) 

1 

binary(3) 

11 

binary(9) 

1001

In [28]:
def binary(n):
    if n == 0:
        print(0, end='')
    elif n == 1:
        print(1, end='')
    else:
        binary(n // 2)
        print(n % 2, end='')

print("binary(0)")
binary(0)
print()  
print("binary(1)")
binary(1)
print()  
print("binary(3)")
binary(3)
print()  
print("binary(9)")
binary(9)
print()

binary(0)
0
binary(1)
1
binary(3)
11
binary(9)
1001

### Question 6
Implement a class named HeadingParser that can be used to parse an HTML document, and retrieve and print all the headings in the document. You should implement your class as a subclass of HTMLParser, defined in Standard Library module html.parser. When fed a string containing HTML code, your class should print the headings, one per line and in the order in which they appear in the 
document. Each heading should be indented as follows: an h1 heading should have indentation 0, and h2 heading should have indentation 1, etc. Test your 
implementation using w3c.html. 
 
infile = open('w3c.html')

content = infile.read() 

infile.close() 

hp = HeadingParser() 

hp.feed(content) 

W3C Mission 

 Principles

In [38]:
from html.parser import HTMLParser

class HeadingParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.headings = []
        self.current_level = 0

    def handle_starttag(self, tag, attrs):
        if tag.startswith('h') and len(tag) > 1 and tag[1].isdigit():
            # Set the current level based on the heading tag number
            self.current_level = int(tag[1])

    def handle_endtag(self, tag):
        if tag.startswith('h') and len(tag) > 1 and tag[1].isdigit():
            # Reset the current level after closing the tag
            self.current_level = 0

    def handle_data(self, data):
        if self.current_level > 0 and data.strip():  # Only add non-empty data
            # Append the heading with indentation based on level
            self.headings.append(" " * (self.current_level - 1) + data.strip())

    def print_headings(self):
        for heading in self.headings:
            print(heading)

# Reading the HTML content from 'w3c.html' and parsing
with open('w3c.html', 'r') as f:
    content = f.read()

hp = HeadingParser()
hp.feed(content)
hp.print_headings()

W3C Mission
 Principles

### Question 7
Implement recursive function webdir() that takes as input: a URL (as a string) and 
non-negative integers depth and indent. Your function should visit every web 
page reachable from the starting URL web page in depth clicks or less, and print 
each web page's URL. As shown below, indentation, specified by indent,  should 
be used to indicate the depth of a URL. 
 
webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html'
 , 2, 0) 
http://reed.cs.depaul.edu/lperkovic/csc242/test1.html 
    http://reed.cs.depaul.edu/lperkovic/csc242/test2.html 
        http://reed.cs.depaul.edu/lperkovic/csc242/test4.html 
    http://reed.cs.depaul.edu/lperkovic/csc242/test3.html 
        http://reed.cs.depaul.edu/lperkovic/csc242/test4.html

In [39]:
import requests
from bs4 import BeautifulSoup


def get_links(url):
    """Returns a list of links on the given web page"""
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    links = []
    for link in soup.find_all('a'):
        href = link.get('href')
        if href is not None:
            links.append(href)
    return links


def webdir(url, depth, indent=0):
    """Recursively visits web pages reachable from the starting URL
    in depth clicks or less and prints each web page's URL."""
    print(' ' * indent + url)
    if depth == 0:
        return
    links = get_links(url)
    for link in links:
        if link.startswith('http'):
            webdir(link, depth-1, indent+1)
            

webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html', 2, 0)

http://reed.cs.depaul.edu/lperkovic/csc242/test1.html

### Question 8
Write SQL queries on the below database table that return:  

a) All the temperature data. 

b) All the cities, but without repetition. 

c) All the records for India. 

d) All the Fall records. 

e) The city, country, and season for which the average rainfall is between 200 
and 400 millimeters. 

f) The city and country for which the average Fall temperature is above 20 
degrees, in increasing temperature order. 

g) The total annual rainfall for Cairo.

h) The total rainfall for each season. 
 
City  Country  Season  Temperature (C) Rainfall (mm) 

Mumbai  India  Winter  24.8  5.9 

Mumbai  India  Spring 28.4  16.2 

Mumbai  India  Summer 27.9  1549.4

Mumbai  India  Fall 27.6  346.0  

London  United Kingdom  Winter 4.2  207.7  

London  United Kingdom  Spring 8.3  169.6 

London  United Kingdom  Summer 15.7  157.0 

London  United Kingdom  Fall 10.4  218.5  

Cairo  Egypt  Winter 13.6  16.5  

Cairo  Egypt  Spring 20.7  6.5 

Cairo  Egypt  Summer 27.7  0.1  

Cairo  Egypt  Fall 22.2  4.5

In [40]:
import sqlite3

conn = sqlite3.connect('weather.db')
cur = conn.cursor()
cur.execute("DROP TABLE IF EXISTS WeatherData")

cur.execute('''CREATE TABLE WeatherData (
                City TEXT,
                Country TEXT,
                Season TEXT,
                Temperature REAL,
                Rainfall REAL)''')

cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Mumbai', 'India', 'Winter', 24.8, 5.9))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Mumbai', 'India', 'Spring', 28.4, 16.2))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Mumbai', 'India', 'Summer', 27.9, 1549.4))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Mumbai', 'India', 'Fall', 27.6, 346.0))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('London', 'United Kingdom', 'Winter', 4.2, 207.7))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('London', 'United Kingdom', 'Spring', 8.3, 169.6))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('London', 'United Kingdom', 'Summer', 15.7, 157.0))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('London', 'United Kingdom', 'Fall', 10.4, 218.5))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Cairo', 'Egypt', 'Winter', 13.6, 16.5))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Cairo', 'Egypt', 'Spring', 20.7, 6.5))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Cairo', 'Egypt', 'Summer', 27.7, 0.1))
cur.execute("INSERT INTO WeatherData (City, Country, Season, Temperature, Rainfall) VALUES (?, ?, ?, ?, ?)", ('Cairo', 'Egypt', 'Fall', 22.2, 4.5))
conn.commit()

conn.close()

In [41]:
import sqlite3

conn = sqlite3.connect('weather.db')
cur = conn.cursor()

cur.execute("SELECT Temperature FROM WeatherData")
print("All temperature data:")
print(cur.fetchall())

cur.execute("SELECT DISTINCT City FROM WeatherData")
print("\nAll cities:")
print(cur.fetchall())

cur.execute("SELECT * FROM WeatherData WHERE Country = 'India'")
print("\nAll records for India:")
print(cur.fetchall())

cur.execute("SELECT * FROM WeatherData WHERE Season = 'Fall'")
print("\nAll Fall records:")
print(cur.fetchall())

cur.execute("SELECT City, Country, Season FROM WeatherData WHERE Rainfall BETWEEN 200 AND 400")
print("\nCity, country, and season with average rainfall between 200 and 400 millimeters:")
print(cur.fetchall())

cur.execute("SELECT City, Country FROM WeatherData WHERE Season = 'Fall' AND Temperature > 20 ORDER BY Temperature ASC")
print("\nCity and country with average Fall temperature above 20 degrees:")
print(cur.fetchall())

cur.execute("SELECT SUM(Rainfall) FROM WeatherData WHERE City = 'Cairo'")
print("\nTotal annual rainfall for Cairo:")
print(cur.fetchone()[0])

cur.execute("SELECT Season, SUM(Rainfall) FROM WeatherData GROUP BY Season")
print("\nTotal rainfall for each season:")
print(cur.fetchall())

conn.close()

All temperature data:
[(24.8,), (28.4,), (27.9,), (27.6,), (4.2,), (8.3,), (15.7,), (10.4,), (13.6,), (20.7,), (27.7,), (22.2,)]

All cities:
[('Mumbai',), ('London',), ('Cairo',)]

All records for India:
[('Mumbai', 'India', 'Winter', 24.8, 5.9), ('Mumbai', 'India', 'Spring', 28.4, 16.2), ('Mumbai', 'India', 'Summer', 27.9, 1549.4), ('Mumbai', 'India', 'Fall', 27.6, 346.0)]

All Fall records:
[('Mumbai', 'India', 'Fall', 27.6, 346.0), ('London', 'United Kingdom', 'Fall', 10.4, 218.5), ('Cairo', 'Egypt', 'Fall', 22.2, 4.5)]

City, country, and season with average rainfall between 200 and 400 millimeters:
[('Mumbai', 'India', 'Fall'), ('London', 'United Kingdom', 'Winter'), ('London', 'United Kingdom', 'Fall')]

City and country with average Fall temperature above 20 degrees:
[('Cairo', 'Egypt'), ('Mumbai', 'India')]

Total annual rainfall for Cairo:
27.6

Total rainfall for each season:
[('Fall', 569.0), ('Spring', 192.29999999999998), ('Summer', 1706.5), ('Winter', 230.1)]

### Question 9
 Suppose list words is defined as follows: 
 
words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 
'the', 'lazy', 'dog'] 

Write list comprehension expressions that use list words and generate the following 
lists: 

a) ['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE', 
'LAZY', 'DOG'] 

b) ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 
'lazy', 'dog'] 

c) [3, 5, 5, 3, 5, 4, 3, 4, 3] (the list of lengths of words in list 
words). 

d) [['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN', 
'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5], 
['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy', 
4], ['DOG', 'dog', 3]] (the list containing a list for every word of list 
words, where each list contains the word in uppercase and lowercase and the 
length of the word.) 

e) ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 
'lazy', 'dog'] (the list of words in list words containing 4 or more 
characters.)

In [2]:
w = ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
w_upper = [word.upper() for word in w]
print(w_upper)

w_lower = [word.lower() for word in w]
print(w_lower)

w_length = [len(word) for word in w]
print(w_length)

w_list = [[word.upper(), word.lower(), len(word)] for word in w]
print(w_list)

w_length_4 = [word for word in w if len(word) >= 4]
print(w_length_4)

['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE', 'LAZY', 'DOG']
['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
[3, 5, 5, 3, 5, 4, 3, 4, 3]
[['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN', 'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5], ['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy', 4], ['DOG', 'dog', 3]]
['quick', 'brown', 'jumps', 'over', 'lazy']